version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: aigotools_mongo
    ports:
      - 27017:27017
    command: mongod --auth
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    networks:
      - aigotools
  minio:
    image: 'quay.io/minio/minio:RELEASE.2023-08-31T15-31-16Z'
    container_name: aigotools_minio
    ports:
      - '9000:9000'
      - '9001:9001'
    command: server --console-address ":9001" http://minio/data{1...2}
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=12345678
    healthcheck:
      test:
        [
          'CMD',
          'curl',
          '-f',
          'http://localhost:9000/minio/health/live'
        ]
      interval: 30s
      timeout: 20s
      retries: 3
networks:
  aigotools:
    driver: bridge
