version: '3'
services:
  aigotools:
    container_name: aigotools
    build: ./packages/aigotools
    ports:
      - '0.0.0.0:3000:3000'
    volumes:
      - ./packages/aigotools/.env:/app/.env

  crawler:
    container_name: crawler
    build: ./packages/crawler
    ports:
      - '0.0.0.0:13000:13000'
    volumes:
      - ./packages/aigotools/.env:/app/.env

  mongo:
    image: mongo:latest
    container_name: aigotools-mongo
    volumes:
      - './volumes/mongo/configdb:/data/configdb'
      - './volumes/mongo/data:/data/db'
    command: mongod --auth
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=aigotools123456

  redis:
    image: redis:latest
    container_name: aigotools-redis
    command: [ 'redis-server', '--requirepass', 'aigotools123456' ]
    volumes:
      - './volumes/redis/redis.conf:/etc/redis/redis.conf'
      - './volumes/redis/data:/data'

  minio:
    image: 'quay.io/minio/minio:RELEASE.2023-08-31T15-31-16Z'
    container_name: aigotools-minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - './volumes/minio/data1:/data1'
      - './volumes/minio/data2:/data2'
    command: server --console-address ":9001" http://minio/data{1...2}
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=aigotools123456
    healthcheck:
      test:
        [
          'CMD',
          'curl',
          '-f',
          'http://localhost:9000/minio/health/live'
        ]
      interval: 30s
      timeout: 20s
      retries: 3
